// <auto-generated />
namespace FIT5032AssignmentProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class orderRatingNoRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderRatingNoRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202210070121513_orderRatingNoRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
